export const players = [
  {
    id: 1337,
    resource_id: null,
    name: 'Lionel Messi',
    age: 34,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Lionel',
    last_name: 'Messi',
    common_name: 'Messi',
    height: 170,
    weight: 72,
    birth_date: '1987-06-24',
    league: 16,
    nation: 52,
    club: 73,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'RW',
    skill_moves: 4,
    weak_foot: 4,
    foot: 'Left',
    attack_work_rate: 'Med',
    defense_work_rate: 'Low',
    total_stats: null,
    total_stats_in_game: null,
    rating: 93,
    rating_average: null,
    pace: 85,
    shooting: 92,
    passing: 91,
    dribbling: 95,
    defending: 34,
    physicality: 65,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/79f743d2-1928-4f5d-b647-379b09b853d1',
    leagueImage:
      'blob:http://localhost:3000/3b34a1bd-265a-4a81-ba06-d24b2f911027',
    clubImage: 'blob:http://localhost:3000/dad173ae-4a3d-4c9e-bda9-0e7c5e9d34a8'
  },
  {
    id: 512,
    resource_id: null,
    name: 'Robert Lewandowski',
    age: 33,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Robert',
    last_name: 'Lewandowski',
    common_name: 'Lewandowski',
    height: 185,
    weight: 81,
    birth_date: '1988-08-21',
    league: 19,
    nation: 37,
    club: 21,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 4,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 92,
    rating_average: null,
    pace: 78,
    shooting: 92,
    passing: 79,
    dribbling: 86,
    defending: 44,
    physicality: 82,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/e25f74e1-5dd4-4864-b93b-4b8fe4e5846a',
    leagueImage:
      'blob:http://localhost:3000/c6b81993-0712-4f1f-bb21-1ff71002907a',
    clubImage: 'blob:http://localhost:3000/4bb45cd6-45e0-4936-b02c-30603512d673'
  },
  {
    id: 1340,
    resource_id: null,
    name: 'Neymar Jr',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Neymar',
    last_name: 'da Silva Santos Jr.',
    common_name: 'Neymar',
    height: 175,
    weight: 68,
    birth_date: '1992-02-05',
    league: 16,
    nation: 54,
    club: 73,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'LW',
    skill_moves: 5,
    weak_foot: 5,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 91,
    rating_average: null,
    pace: 91,
    shooting: 83,
    passing: 86,
    dribbling: 94,
    defending: 37,
    physicality: 63,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/d8b4c59c-9d9d-4ffc-b206-2e3a022a546a',
    leagueImage:
      'blob:http://localhost:3000/8bf11185-01e9-48c4-9ea4-105c65388c68',
    clubImage: 'blob:http://localhost:3000/0925b08d-b2c3-495e-ac8a-28e69dbb9bce'
  },
  {
    id: 2627,
    resource_id: null,
    name: 'Jan Oblak',
    age: 29,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Jan',
    last_name: 'Oblak',
    common_name: 'Oblak',
    height: 188,
    weight: 87,
    birth_date: '1993-01-07',
    league: 53,
    nation: 44,
    club: 240,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 91,
    rating_average: null,
    pace: 51,
    shooting: 19,
    passing: 31,
    dribbling: 49,
    defending: 18,
    physicality: 57,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/17858472-bd70-4d48-b6d4-0628ca2164a0',
    leagueImage:
      'blob:http://localhost:3000/76ad7c87-fe59-4838-883f-320334920c87',
    clubImage: 'blob:http://localhost:3000/430b3219-2361-4613-a024-fb7d8b0eedbf'
  },
  {
    id: 268,
    resource_id: null,
    name: 'Cristiano Ronaldo',
    age: 37,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'C. Ronaldo',
    last_name: 'dos Santos Aveiro',
    common_name: 'Ronaldo',
    height: 187,
    weight: 83,
    birth_date: '1985-02-05',
    league: 13,
    nation: 38,
    club: 11,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 5,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Low',
    total_stats: null,
    total_stats_in_game: null,
    rating: 91,
    rating_average: null,
    pace: 87,
    shooting: 93,
    passing: 82,
    dribbling: 88,
    defending: 34,
    physicality: 75,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/6ac8a790-8541-49f9-b139-249ba4a46592',
    leagueImage:
      'blob:http://localhost:3000/9128a3e4-f5e7-401b-a714-38722edfa416',
    clubImage: 'blob:http://localhost:3000/753cb716-4738-43a6-885c-b59b4b4326b5'
  },
  {
    id: 1339,
    resource_id: null,
    name: 'Kylian Mbappé',
    age: 23,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Kylian',
    last_name: 'Mbappé',
    common_name: 'Mbappé',
    height: 182,
    weight: 73,
    birth_date: '1998-12-20',
    league: 16,
    nation: 18,
    club: 73,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 5,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Low',
    total_stats: null,
    total_stats_in_game: null,
    rating: 91,
    rating_average: null,
    pace: 97,
    shooting: 88,
    passing: 80,
    dribbling: 92,
    defending: 36,
    physicality: 77,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/8c294bd0-9b78-47d0-bf52-17c3cc548709',
    leagueImage:
      'blob:http://localhost:3000/4b7fb945-35aa-43c3-b0f9-0aa4da5f2603',
    clubImage: 'blob:http://localhost:3000/7f6b64fb-452c-40b5-85f8-f3d1ed31e133'
  },
  {
    id: 238,
    resource_id: null,
    name: 'Kevin De Bruyne',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Kevin',
    last_name: 'De Bruyne',
    common_name: 'De Bruyne',
    height: 181,
    weight: 70,
    birth_date: '1991-06-28',
    league: 13,
    nation: 7,
    club: 10,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CM',
    skill_moves: 4,
    weak_foot: 5,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 91,
    rating_average: null,
    pace: 76,
    shooting: 86,
    passing: 93,
    dribbling: 88,
    defending: 64,
    physicality: 78,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/17631a8a-323e-4c81-a8ad-fcdf3cd55f38',
    leagueImage:
      'blob:http://localhost:3000/b61418bb-cf80-4f62-a46a-3669da07e14c',
    clubImage: 'blob:http://localhost:3000/ae46f9b7-3d55-40bb-a3fc-a616ee17e3e9'
  },
  {
    id: 514,
    resource_id: null,
    name: 'Manuel Neuer',
    age: 36,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Manuel',
    last_name: 'Neuer',
    common_name: 'Neuer',
    height: 193,
    weight: 93,
    birth_date: '1986-03-27',
    league: 19,
    nation: 21,
    club: 21,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 90,
    rating_average: null,
    pace: 57,
    shooting: 27,
    passing: 39,
    dribbling: 49,
    defending: 18,
    physicality: 57,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/14dc0182-4e64-457e-8553-a088cb597a5c',
    leagueImage:
      'blob:http://localhost:3000/e7daf543-29c5-47be-a6b9-347ae4e8e4c2',
    clubImage: 'blob:http://localhost:3000/3cc5c425-cc91-48b9-9b5f-c904523f4b07'
  },
  {
    id: 2653,
    resource_id: null,
    name: 'ter Stegen',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Marc-André',
    last_name: 'ter Stegen',
    common_name: 'ter Stegen',
    height: 187,
    weight: 85,
    birth_date: '1992-04-30',
    league: 53,
    nation: 21,
    club: 241,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 90,
    rating_average: null,
    pace: 44,
    shooting: 23,
    passing: 40,
    dribbling: 43,
    defending: 16,
    physicality: 58,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/8229062d-d0fa-4f4c-be2a-fd858de74d87',
    leagueImage:
      'blob:http://localhost:3000/6ab630ac-ec4c-4c10-9509-38f2590888f6',
    clubImage: 'blob:http://localhost:3000/d4da29be-a569-4ebf-a1df-880af7a6cb96'
  },
  {
    id: 114,
    resource_id: null,
    name: "N'Golo Kanté",
    age: 31,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: "N'Golo",
    last_name: 'Kanté',
    common_name: 'Kanté',
    height: 168,
    weight: 70,
    birth_date: '1991-03-29',
    league: 13,
    nation: 18,
    club: 5,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CDM',
    skill_moves: 2,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 90,
    rating_average: null,
    pace: 78,
    shooting: 66,
    passing: 75,
    dribbling: 82,
    defending: 87,
    physicality: 83,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/df87afa4-41e9-41b5-8964-8de70b3be90e',
    leagueImage:
      'blob:http://localhost:3000/fc2ce7f3-bdcf-4af4-9412-9216a1262aa5',
    clubImage: 'blob:http://localhost:3000/bb71e3d7-89af-46da-9c35-d99de532b5bd'
  },
  {
    id: 449,
    resource_id: null,
    name: 'Harry Kane',
    age: 28,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Harry',
    last_name: 'Kane',
    common_name: 'Kane',
    height: 188,
    weight: 89,
    birth_date: '1993-07-28',
    league: 13,
    nation: 14,
    club: 18,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 3,
    weak_foot: 5,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 90,
    rating_average: null,
    pace: 70,
    shooting: 91,
    passing: 83,
    dribbling: 83,
    defending: 47,
    physicality: 83,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/6e3941e9-e4ef-465c-b1df-2802887152c9',
    leagueImage:
      'blob:http://localhost:3000/f8f27822-3ec7-4939-acd2-8b878285ca06',
    clubImage: 'blob:http://localhost:3000/847a3862-6419-469f-a008-42b85ba1be3b'
  },
  {
    id: 515,
    resource_id: null,
    name: 'Joshua Kimmich',
    age: 27,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Joshua',
    last_name: 'Kimmich',
    common_name: 'Kimmich',
    height: 177,
    weight: 75,
    birth_date: '1995-02-08',
    league: 19,
    nation: 21,
    club: 21,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CDM',
    skill_moves: 3,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 70,
    shooting: 73,
    passing: 86,
    dribbling: 84,
    defending: 83,
    physicality: 79,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/203a505b-3a64-40dc-94a8-a3551ea838d9',
    leagueImage:
      'blob:http://localhost:3000/07800dc8-86db-4583-b5fe-178990402a43',
    clubImage: 'blob:http://localhost:3000/067939ba-fdf3-4222-9381-3b6b6a761535'
  },
  {
    id: 1342,
    resource_id: null,
    name: 'Gianluigi Donnarumma',
    age: 23,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Gianluigi',
    last_name: 'Donnarumma',
    common_name: 'Donnarumma',
    height: 196,
    weight: 90,
    birth_date: '1999-02-25',
    league: 16,
    nation: 27,
    club: 73,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 52,
    shooting: 22,
    passing: 28,
    dribbling: 49,
    defending: 17,
    physicality: 52,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/1abcd643-9fa3-4ffe-b05a-a39730b5ec4a',
    leagueImage:
      'blob:http://localhost:3000/d00a654b-1507-41f0-a2aa-b170e32a453a',
    clubImage: 'blob:http://localhost:3000/25a5d39a-a541-4aae-a979-83399340f94a'
  },
  {
    id: 2685,
    resource_id: null,
    name: 'Casemiro',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Carlos Henrique',
    last_name: 'Venancio Casimiro',
    common_name: 'Casemiro',
    height: 185,
    weight: 84,
    birth_date: '1992-02-23',
    league: 53,
    nation: 54,
    club: 243,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CDM',
    skill_moves: 2,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 65,
    shooting: 73,
    passing: 76,
    dribbling: 73,
    defending: 86,
    physicality: 90,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/9c2cdc4c-fa7a-4168-821f-5b52f4550965',
    leagueImage:
      'blob:http://localhost:3000/1fbea617-a73f-41d4-8ffa-3a791923099e',
    clubImage: 'blob:http://localhost:3000/1c3fb2c4-2eaf-4909-bdf6-a5b8ed4696a7'
  },
  {
    id: 2686,
    resource_id: null,
    name: 'Thibaut Courtois',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Thibaut',
    last_name: 'Courtois',
    common_name: 'Courtois',
    height: 199,
    weight: 96,
    birth_date: '1992-05-11',
    league: 53,
    nation: 7,
    club: 243,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 3,
    foot: 'Left',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 47,
    shooting: 23,
    passing: 27,
    dribbling: 45,
    defending: 16,
    physicality: 49,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/45b63ba6-8baf-4a78-8930-8a77451551b1',
    leagueImage:
      'blob:http://localhost:3000/767ce979-a6c5-438e-a938-ece49a56fad4',
    clubImage: 'blob:http://localhost:3000/ed8357c3-b54c-43ae-8133-1dd570b84c67'
  },
  {
    id: 2687,
    resource_id: null,
    name: 'Karim Benzema',
    age: 34,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Karim',
    last_name: 'Benzema',
    common_name: 'Benzema',
    height: 185,
    weight: 81,
    birth_date: '1987-12-19',
    league: 53,
    nation: 18,
    club: 243,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CF',
    skill_moves: 4,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 76,
    shooting: 86,
    passing: 81,
    dribbling: 87,
    defending: 39,
    physicality: 77,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/75f20c3d-4c7b-4107-8f7c-3a07b8c4b095',
    leagueImage:
      'blob:http://localhost:3000/c37d0074-f9e7-45f8-a6d5-ed565ebeef20',
    clubImage: 'blob:http://localhost:3000/3f344260-8770-47e7-9951-43f44c5fbb84'
  },
  {
    id: 450,
    resource_id: null,
    name: 'Heung Min Son',
    age: 29,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Heung Min',
    last_name: 'Son',
    common_name: 'Son',
    height: 183,
    weight: 78,
    birth_date: '1992-07-08',
    league: 13,
    nation: 167,
    club: 18,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'LM',
    skill_moves: 4,
    weak_foot: 5,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 88,
    shooting: 87,
    passing: 82,
    dribbling: 86,
    defending: 43,
    physicality: 69,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/12450a3c-13d4-4794-8e7f-f7433e1701c4',
    leagueImage:
      'blob:http://localhost:3000/fc6fe2c9-75c4-45e3-bd69-6d85740ec0ee',
    clubImage: 'blob:http://localhost:3000/00875244-709c-454e-8c8b-99624fa46c00'
  },
  {
    id: 206,
    resource_id: null,
    name: 'Sadio Mané',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Sadio',
    last_name: 'Mané',
    common_name: 'Mané',
    height: 175,
    weight: 69,
    birth_date: '1992-04-10',
    league: 13,
    nation: 136,
    club: 9,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'LW',
    skill_moves: 4,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 91,
    shooting: 83,
    passing: 80,
    dribbling: 89,
    defending: 44,
    physicality: 77,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/ea6dffbe-aefb-49a4-a981-7ba398a1c08b',
    leagueImage:
      'blob:http://localhost:3000/617bc0f5-b64b-46bc-8928-e55aee7e19f0',
    clubImage: 'blob:http://localhost:3000/48172d3d-f58f-46ac-a7c8-73d46d39c404'
  },
  {
    id: 207,
    resource_id: null,
    name: 'Alisson',
    age: 29,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Alisson',
    last_name: 'Ramses Becker',
    common_name: 'Alisson',
    height: 191,
    weight: 91,
    birth_date: '1992-10-02',
    league: 13,
    nation: 54,
    club: 9,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 51,
    shooting: 24,
    passing: 34,
    dribbling: 44,
    defending: 18,
    physicality: 47,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/51391989-d124-4213-a61d-658178140e93',
    leagueImage:
      'blob:http://localhost:3000/2fad2272-45dd-4806-94de-2cdfcbb73e33',
    clubImage: 'blob:http://localhost:3000/aae76960-112f-46f6-98f5-991e6ccc7855'
  },
  {
    id: 208,
    resource_id: null,
    name: 'Virgil van Dijk',
    age: 30,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Virgil',
    last_name: 'van Dijk',
    common_name: 'van Dijk',
    height: 193,
    weight: 92,
    birth_date: '1991-07-08',
    league: 13,
    nation: 34,
    club: 9,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CB',
    skill_moves: 2,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 78,
    shooting: 60,
    passing: 71,
    dribbling: 72,
    defending: 91,
    physicality: 84,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/47d6a0d6-4e43-495e-8737-9eb5e6c6b502',
    leagueImage:
      'blob:http://localhost:3000/3e2db3a8-c611-451a-a12e-a24d66e799ae',
    clubImage: 'blob:http://localhost:3000/291dbc39-4f71-45ab-a59f-cbeb33992873'
  },
  {
    id: 209,
    resource_id: null,
    name: 'Mohamed Salah',
    age: 29,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Mohamed',
    last_name: 'Salah',
    common_name: 'Salah',
    height: 175,
    weight: 71,
    birth_date: '1992-06-15',
    league: 13,
    nation: 111,
    club: 9,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'RW',
    skill_moves: 4,
    weak_foot: 3,
    foot: 'Left',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 90,
    shooting: 87,
    passing: 81,
    dribbling: 90,
    defending: 45,
    physicality: 75,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/130c3c82-382c-4d62-bf95-39a566d739b8',
    leagueImage:
      'blob:http://localhost:3000/f3efbda3-ae1a-40c5-99a6-c903c51e2e7b',
    clubImage: 'blob:http://localhost:3000/01da9b8b-beeb-4017-aa9a-3bc93b5c97c0'
  },
  {
    id: 239,
    resource_id: null,
    name: 'Ederson',
    age: 28,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Ederson',
    last_name: 'Santana de Moraes',
    common_name: 'Ederson',
    height: 188,
    weight: 86,
    birth_date: '1993-08-17',
    league: 13,
    nation: 54,
    club: 10,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 3,
    foot: 'Left',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 89,
    rating_average: null,
    pace: 63,
    shooting: 31,
    passing: 42,
    dribbling: 51,
    defending: 18,
    physicality: 55,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/4d7b74d5-6491-48ed-a5ca-8b37fc1afca4',
    leagueImage:
      'blob:http://localhost:3000/150c49fe-51ca-486f-97be-6bdd8e8e4982',
    clubImage: 'blob:http://localhost:3000/ba11c3ca-0a4f-4ff2-80e8-efe6a4ce6d59'
  },
  {
    id: 2628,
    resource_id: null,
    name: 'Luis Suárez',
    age: 35,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Luis',
    last_name: 'Suárez',
    common_name: 'Suárez',
    height: 182,
    weight: 83,
    birth_date: '1987-01-24',
    league: 53,
    nation: 60,
    club: 240,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 3,
    weak_foot: 4,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 72,
    shooting: 90,
    passing: 82,
    dribbling: 84,
    defending: 47,
    physicality: 83,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/7bd1c943-943e-4aab-8895-1ace68ff9df8',
    leagueImage:
      'blob:http://localhost:3000/8368fe66-7562-4fd1-991c-c2416f7372c7',
    clubImage: 'blob:http://localhost:3000/ed0f055c-3194-4a6e-91d0-0ead4014cf23'
  },
  {
    id: 2688,
    resource_id: null,
    name: 'Toni Kroos',
    age: 32,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Toni',
    last_name: 'Kroos',
    common_name: 'Kroos',
    height: 183,
    weight: 76,
    birth_date: '1990-01-04',
    league: 53,
    nation: 21,
    club: 243,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CM',
    skill_moves: 3,
    weak_foot: 5,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 53,
    shooting: 81,
    passing: 91,
    dribbling: 81,
    defending: 71,
    physicality: 68,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/4dde5d93-0ac7-4266-b512-4464e5f948c8',
    leagueImage:
      'blob:http://localhost:3000/52bc44cb-136b-48ab-8f18-439b534e21cc',
    clubImage: 'blob:http://localhost:3000/cc2c05a6-1fdb-42fc-8728-ce7ed1af6004'
  },
  {
    id: 269,
    resource_id: null,
    name: 'Bruno Fernandes',
    age: 27,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Bruno Miguel',
    last_name: 'Borges Fernandes',
    common_name: 'Bruno Fernandes',
    height: 179,
    weight: 69,
    birth_date: '1994-09-08',
    league: 13,
    nation: 38,
    club: 11,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CAM',
    skill_moves: 4,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 75,
    shooting: 86,
    passing: 89,
    dribbling: 84,
    defending: 70,
    physicality: 77,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/7b674eb8-dec3-4812-bed7-2448a3b82dd8',
    leagueImage:
      'blob:http://localhost:3000/949a67fd-1c99-4655-8cff-1f6067a78eb6',
    clubImage: 'blob:http://localhost:3000/6b2b1ae3-8b19-4af6-9954-1ba84f0893df'
  },
  {
    id: 539,
    resource_id: null,
    name: 'Erling Haaland',
    age: 21,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Erling',
    last_name: 'Haaland',
    common_name: 'Haaland',
    height: 194,
    weight: 94,
    birth_date: '2000-07-21',
    league: 19,
    nation: 36,
    club: 22,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 3,
    weak_foot: 3,
    foot: 'Left',
    attack_work_rate: 'High',
    defense_work_rate: 'High',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 89,
    shooting: 91,
    passing: 65,
    dribbling: 80,
    defending: 45,
    physicality: 88,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/5895fdd9-bbb2-441b-9944-d0e60e24bdcd',
    leagueImage:
      'blob:http://localhost:3000/7cf06580-33db-4144-8d80-ed623adff1fe',
    clubImage: 'blob:http://localhost:3000/ad36e21b-4687-4155-99f3-d68185b1f319'
  },
  {
    id: 1343,
    resource_id: null,
    name: 'Sergio Ramos García',
    age: 36,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Sergio',
    last_name: 'Ramos García',
    common_name: 'Sergio Ramos',
    height: 184,
    weight: 82,
    birth_date: '1986-03-30',
    league: 16,
    nation: 45,
    club: 73,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'CB',
    skill_moves: 3,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 70,
    shooting: 70,
    passing: 76,
    dribbling: 74,
    defending: 88,
    physicality: 84,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/5d44cbdc-6da4-4337-8c63-ad3c5502956b',
    leagueImage:
      'blob:http://localhost:3000/21c1548f-e451-4869-8f89-9c448e73fc43',
    clubImage: 'blob:http://localhost:3000/c9c4277b-a30e-4643-a54b-533da591b7ab'
  },
  {
    id: 1344,
    resource_id: null,
    name: 'Keylor Navas',
    age: 35,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Keylor',
    last_name: 'Navas',
    common_name: 'Navas',
    height: 185,
    weight: 80,
    birth_date: '1986-12-15',
    league: 16,
    nation: 72,
    club: 73,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'GK',
    skill_moves: 1,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 53,
    shooting: 22,
    passing: 32,
    dribbling: 52,
    defending: 17,
    physicality: 55,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/19a2bee4-1056-4c37-a285-bc8434cf5601',
    leagueImage:
      'blob:http://localhost:3000/77cf1c33-9e6a-4624-9879-7b0f210bc0d4',
    clubImage: 'blob:http://localhost:3000/8d75610f-9ec6-4f4b-89fa-2a5b5253b57d'
  },
  {
    id: 116,
    resource_id: null,
    name: 'Romelu Lukaku',
    age: 29,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Romelu',
    last_name: 'Lukaku',
    common_name: 'Lukaku',
    height: 191,
    weight: 94,
    birth_date: '1993-05-13',
    league: 13,
    nation: 7,
    club: 5,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'ST',
    skill_moves: 3,
    weak_foot: 4,
    foot: 'Left',
    attack_work_rate: 'Med',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 84,
    shooting: 87,
    passing: 74,
    dribbling: 78,
    defending: 39,
    physicality: 83,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/cb29bc8d-9b45-439b-8ef4-fa9003dd3da8',
    leagueImage:
      'blob:http://localhost:3000/fed1c0ec-a91d-4458-a65e-4665de1615c6',
    clubImage: 'blob:http://localhost:3000/977b1f1c-dadd-4abd-bfcd-33772796249b'
  },
  {
    id: 240,
    resource_id: null,
    name: 'Raheem Sterling',
    age: 27,
    resource_base_id: null,
    fut_bin_id: null,
    fut_wiz_id: null,
    first_name: 'Raheem',
    last_name: 'Sterling',
    common_name: 'Sterling',
    height: 170,
    weight: 69,
    birth_date: '1994-12-08',
    league: 13,
    nation: 14,
    club: 10,
    rarity: 1,
    traits: [],
    specialities: [],
    position: 'LW',
    skill_moves: 4,
    weak_foot: 3,
    foot: 'Right',
    attack_work_rate: 'High',
    defense_work_rate: 'Med',
    total_stats: null,
    total_stats_in_game: null,
    rating: 88,
    rating_average: null,
    pace: 91,
    shooting: 82,
    passing: 79,
    dribbling: 87,
    defending: 45,
    physicality: 66,
    pace_attributes: null,
    shooting_attributes: null,
    passing_attributes: null,
    dribbling_attributes: null,
    defending_attributes: null,
    physicality_attributes: null,
    goalkeeper_attributes: null,
    playerImage:
      'blob:http://localhost:3000/1ee8d68d-27f1-4d23-bb9d-11ea19a9b8a9',
    leagueImage:
      'blob:http://localhost:3000/220d3352-8f63-4295-bc66-a477e8952dbd',
    clubImage: 'blob:http://localhost:3000/ac137bd8-c83c-46d4-af63-f881a88b2f2d'
  }
]
